// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sanguosha.com/werewolf/gameproto/opcode/client.proto

package com.mapi.werewolf.opcode;

public final class ClientOuterClass {
  private ClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.mapi.werewolf.opcode.Client}
   */
  public enum Client
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ClientInvaildOpCode = 0;</code>
     */
    ClientInvaildOpCode(0),
    /**
     * <pre>
     * gate需要解析的协议
     * </pre>
     *
     * <code>ReqHeartBeat = 1;</code>
     */
    ReqHeartBeat(1),
    /**
     * <code>RespHeartBeat = 2;</code>
     */
    RespHeartBeat(2),
    /**
     * <code>ReqLogin = 3;</code>
     */
    ReqLogin(3),
    /**
     * <code>RespLogin = 4;</code>
     */
    RespLogin(4),
    /**
     * <pre>
     * 客户端请求退出
     * </pre>
     *
     * <code>ReqLogout = 5;</code>
     */
    ReqLogout(5),
    /**
     * <pre>
     * 服务器踢人
     * </pre>
     *
     * <code>NoticeLogout = 6;</code>
     */
    NoticeLogout(6),
    /**
     * <code>S_MessageInChannel = 11;</code>
     */
    S_MessageInChannel(11),
    /**
     * <code>ROUTE_ENTITY_BEGIN = 200;</code>
     */
    ROUTE_ENTITY_BEGIN(200),
    /**
     * <code>C_ReqUserData = 201;</code>
     */
    C_ReqUserData(201),
    /**
     * <code>S_RespUserData = 202;</code>
     */
    S_RespUserData(202),
    /**
     * <code>C_ReqInitUserData = 203;</code>
     */
    C_ReqInitUserData(203),
    /**
     * <code>S_RespInitUserData = 204;</code>
     */
    S_RespInitUserData(204),
    /**
     * <code>C_ReqChangeAvatar = 205;</code>
     */
    C_ReqChangeAvatar(205),
    /**
     * <code>S_ResChangeAvatar = 206;</code>
     */
    S_ResChangeAvatar(206),
    /**
     * <code>C_ReqGameRecords = 210;</code>
     */
    C_ReqGameRecords(210),
    /**
     * <code>S_RespGameRecords = 211;</code>
     */
    S_RespGameRecords(211),
    /**
     * <code>S_NoticeUserExpLevel = 212;</code>
     */
    S_NoticeUserExpLevel(212),
    /**
     * <code>C_ReqBindAccount = 213;</code>
     */
    C_ReqBindAccount(213),
    /**
     * <code>S_RespBindAccount = 214;</code>
     */
    S_RespBindAccount(214),
    /**
     * <code>C_ReqUserMatchData = 215;</code>
     */
    C_ReqUserMatchData(215),
    /**
     * <code>S_RespUserMatchData = 216;</code>
     */
    S_RespUserMatchData(216),
    /**
     * <code>C_ReqUserMatchGameRecords = 217;</code>
     */
    C_ReqUserMatchGameRecords(217),
    /**
     * <code>S_RespUserMatchGameRecords = 218;</code>
     */
    S_RespUserMatchGameRecords(218),
    /**
     * <code>C_ReqGoodsByCategory = 219;</code>
     */
    C_ReqGoodsByCategory(219),
    /**
     * <code>S_RespGoodsByCategory = 220;</code>
     */
    S_RespGoodsByCategory(220),
    /**
     * <code>C_ReqAllGoods = 221;</code>
     */
    C_ReqAllGoods(221),
    /**
     * <code>S_RespAllGoods = 222;</code>
     */
    S_RespAllGoods(222),
    /**
     * <code>C_ReqAllTasks = 223;</code>
     */
    C_ReqAllTasks(223),
    /**
     * <code>S_RespAllTasks = 224;</code>
     */
    S_RespAllTasks(224),
    /**
     * <code>S_NtfTaskState = 225;</code>
     */
    S_NtfTaskState(225),
    /**
     * <code>C_ReqChangeTask = 226;</code>
     */
    C_ReqChangeTask(226),
    /**
     * <code>S_RespChangeTask = 227;</code>
     */
    S_RespChangeTask(227),
    /**
     * <code>C_ReqMyActivity = 228;</code>
     */
    C_ReqMyActivity(228),
    /**
     * <code>S_RespMyActivity = 229;</code>
     */
    S_RespMyActivity(229),
    /**
     * <code>C_ReqEditSignature = 230;</code>
     */
    C_ReqEditSignature(230),
    /**
     * <code>S_RespEditSignature = 231;</code>
     */
    S_RespEditSignature(231),
    /**
     * <code>C_ReqUpLoadFigure = 232;</code>
     */
    C_ReqUpLoadFigure(232),
    /**
     * <code>S_RespUpLoadFigure = 233;</code>
     */
    S_RespUpLoadFigure(233),
    /**
     * <code>ROUTE_ENTITY_END = 999;</code>
     */
    ROUTE_ENTITY_END(999),
    /**
     * <code>ROUTER_LOBBY_BEGIN = 1000;</code>
     */
    ROUTER_LOBBY_BEGIN(1000),
    /**
     * <code>C_ReqQuickJoinRoom = 1001;</code>
     */
    C_ReqQuickJoinRoom(1001),
    /**
     * <code>C_ReqJoinRoom = 1027;</code>
     */
    C_ReqJoinRoom(1027),
    /**
     * <code>S_RespJoinRoom = 1002;</code>
     */
    S_RespJoinRoom(1002),
    /**
     * <code>C_ReqQuitRoom = 1003;</code>
     */
    C_ReqQuitRoom(1003),
    /**
     * <code>S_RespQuitRoom = 1004;</code>
     */
    S_RespQuitRoom(1004),
    /**
     * <code>C_ReqCreateRoom = 1028;</code>
     */
    C_ReqCreateRoom(1028),
    /**
     * <code>S_RespCreateRoom = 1029;</code>
     */
    S_RespCreateRoom(1029),
    /**
     * <code>C_ReqApplyAddFriend = 1008;</code>
     */
    C_ReqApplyAddFriend(1008),
    /**
     * <code>S_ResApplyAddFriend = 1009;</code>
     */
    S_ResApplyAddFriend(1009),
    /**
     * <code>C_ReqConfirmAddFriend = 1010;</code>
     */
    C_ReqConfirmAddFriend(1010),
    /**
     * <code>S_ResConfirmAddFriend = 1011;</code>
     */
    S_ResConfirmAddFriend(1011),
    /**
     * <code>C_ReqDelFriend = 1012;</code>
     */
    C_ReqDelFriend(1012),
    /**
     * <code>S_ResDelFriend = 1013;</code>
     */
    S_ResDelFriend(1013),
    /**
     * <code>C_ReqFriendChat = 1014;</code>
     */
    C_ReqFriendChat(1014),
    /**
     * <code>S_ResFriendChat = 1015;</code>
     */
    S_ResFriendChat(1015),
    /**
     * <code>C_ReqFollowFriend = 1016;</code>
     */
    C_ReqFollowFriend(1016),
    /**
     * <code>S_ResFollowFriend = 1017;</code>
     */
    S_ResFollowFriend(1017),
    /**
     * <code>C_ReqFriendData = 1018;</code>
     */
    C_ReqFriendData(1018),
    /**
     * <code>S_ResFriendData = 1019;</code>
     */
    S_ResFriendData(1019),
    /**
     * <code>C_ReqFriendList = 1020;</code>
     */
    C_ReqFriendList(1020),
    /**
     * <code>S_ResFriendList = 1021;</code>
     */
    S_ResFriendList(1021),
    /**
     * <code>S_NoticeApplyAddFriend = 1022;</code>
     */
    S_NoticeApplyAddFriend(1022),
    /**
     * <code>S_NoticeConfirmAddFriend = 1023;</code>
     */
    S_NoticeConfirmAddFriend(1023),
    /**
     * <code>S_NoticeDelFriend = 1024;</code>
     */
    S_NoticeDelFriend(1024),
    /**
     * <code>C_ReqFriendStatus = 1025;</code>
     */
    C_ReqFriendStatus(1025),
    /**
     * <code>S_ResFriendStatus = 1026;</code>
     */
    S_ResFriendStatus(1026),
    /**
     * <code>C_InviteJoinRoom = 1030;</code>
     */
    C_InviteJoinRoom(1030),
    /**
     * <code>S_InviteJoinRoomResult = 1031;</code>
     */
    S_InviteJoinRoomResult(1031),
    /**
     * <code>S_NoticeInviteToJoinRoom = 1032;</code>
     */
    S_NoticeInviteToJoinRoom(1032),
    /**
     * <code>S_NoticeGameFreeze = 1033;</code>
     */
    S_NoticeGameFreeze(1033),
    /**
     * <code>C_ReqJoinMatch = 1035;</code>
     */
    C_ReqJoinMatch(1035),
    /**
     * <code>S_RespJoinMatch = 1036;</code>
     */
    S_RespJoinMatch(1036),
    /**
     * <code>C_ReqCancelMatch = 1037;</code>
     */
    C_ReqCancelMatch(1037),
    /**
     * <code>S_RespCancelMatch = 1038;</code>
     */
    S_RespCancelMatch(1038),
    /**
     * <code>C_ReqUserSignUpMatch = 1039;</code>
     */
    C_ReqUserSignUpMatch(1039),
    /**
     * <code>S_RespUserSignUpMatch = 1040;</code>
     */
    S_RespUserSignUpMatch(1040),
    /**
     * <code>C_ReqJoinChatChannel = 1041;</code>
     */
    C_ReqJoinChatChannel(1041),
    /**
     * <code>S_RespJoinChatChannel = 1042;</code>
     */
    S_RespJoinChatChannel(1042),
    /**
     * <code>C_ReqChatChannelList = 1043;</code>
     */
    C_ReqChatChannelList(1043),
    /**
     * <code>S_RespChatChannelList = 1044;</code>
     */
    S_RespChatChannelList(1044),
    /**
     * <code>C_SendMessageInChannel = 1045;</code>
     */
    C_SendMessageInChannel(1045),
    /**
     * <code>C_ReqQuitChatChannel = 1046;</code>
     */
    C_ReqQuitChatChannel(1046),
    /**
     * <code>S_RespQuitChatChannel = 1047;</code>
     */
    S_RespQuitChatChannel(1047),
    /**
     * <code>C_ReqCreateMatchRoom = 1048;</code>
     */
    C_ReqCreateMatchRoom(1048),
    /**
     * <code>S_RespCreateMatchRoom = 1049;</code>
     */
    S_RespCreateMatchRoom(1049),
    /**
     * <code>C_ReqJoinMatchRoom = 1050;</code>
     */
    C_ReqJoinMatchRoom(1050),
    /**
     * <code>S_RespJoinMatchRoom = 1051;</code>
     */
    S_RespJoinMatchRoom(1051),
    /**
     * <code>ROUTER_LOBBY_END = 1999;</code>
     */
    ROUTER_LOBBY_END(1999),
    /**
     * <code>ROUTER_GAME_BEGIN = 2000;</code>
     */
    ROUTER_GAME_BEGIN(2000),
    /**
     * <code>C_ReportClientReadyForGame = 2001;</code>
     */
    C_ReportClientReadyForGame(2001),
    /**
     * <code>C_ReqReady = 2002;</code>
     */
    C_ReqReady(2002),
    /**
     * <code>S_RespReady = 2003;</code>
     */
    S_RespReady(2003),
    /**
     * <code>C_ReqCancelReady = 2004;</code>
     */
    C_ReqCancelReady(2004),
    /**
     * <code>S_RespCancelReady = 2005;</code>
     */
    S_RespCancelReady(2005),
    /**
     * <code>C_ReqRoomStartGame = 2006;</code>
     */
    C_ReqRoomStartGame(2006),
    /**
     * <code>S_RespRoomStartGame = 2007;</code>
     */
    S_RespRoomStartGame(2007),
    /**
     * <code>S_IsRoomAbleStartGame = 2020;</code>
     */
    S_IsRoomAbleStartGame(2020),
    /**
     * <code>C_ReqKickUser = 2008;</code>
     */
    C_ReqKickUser(2008),
    /**
     * <code>S_RespKickUser = 2009;</code>
     */
    S_RespKickUser(2009),
    /**
     * <code>S_NoticeBeKicked = 2010;</code>
     */
    S_NoticeBeKicked(2010),
    /**
     * <code>S_SyncRoomState = 2011;</code>
     */
    S_SyncRoomState(2011),
    /**
     * <code>S_UserJoin = 2012;</code>
     */
    S_UserJoin(2012),
    /**
     * <code>S_UserQuit = 2013;</code>
     */
    S_UserQuit(2013),
    /**
     * <code>S_UserReady = 2014;</code>
     */
    S_UserReady(2014),
    /**
     * <code>S_UserConnect = 2015;</code>
     */
    S_UserConnect(2015),
    /**
     * <code>C_ReportUserLeaveState = 2034;</code>
     */
    C_ReportUserLeaveState(2034),
    /**
     * <code>S_NewRoomOwner = 2016;</code>
     */
    S_NewRoomOwner(2016),
    /**
     * <code>C_SendMessageInRoom = 2017;</code>
     */
    C_SendMessageInRoom(2017),
    /**
     * <code>S_UserMessageInRoom = 2018;</code>
     */
    S_UserMessageInRoom(2018),
    /**
     * <code>S_GameSyncOK = 2019;</code>
     */
    S_GameSyncOK(2019),
    /**
     * <code>C_RoomSettingEnableSpeakInterrupt = 2200;</code>
     */
    C_RoomSettingEnableSpeakInterrupt(2200),
    /**
     * <code>S_RoomSettingEnableSpeakInterrupt = 2201;</code>
     */
    S_RoomSettingEnableSpeakInterrupt(2201),
    /**
     * <code>C_RoomSettingUserLevelLimit = 2202;</code>
     */
    C_RoomSettingUserLevelLimit(2202),
    /**
     * <code>S_RoomSettingUserLevelLimit = 2203;</code>
     */
    S_RoomSettingUserLevelLimit(2203),
    /**
     * <code>C_RoomSettingPWD = 2204;</code>
     */
    C_RoomSettingPWD(2204),
    /**
     * <code>S_RoomSettingPWD = 2205;</code>
     */
    S_RoomSettingPWD(2205),
    /**
     * <code>C_RoomSettingEnableSpectate = 2206;</code>
     */
    C_RoomSettingEnableSpectate(2206),
    /**
     * <code>S_RoomSettingEnableSpectate = 2207;</code>
     */
    S_RoomSettingEnableSpectate(2207),
    /**
     * <code>C_ReqChangeSeat = 2208;</code>
     */
    C_ReqChangeSeat(2208),
    /**
     * <code>S_RespChangeSeat = 2209;</code>
     */
    S_RespChangeSeat(2209),
    /**
     * <code>S_UserChangeSeat = 2210;</code>
     */
    S_UserChangeSeat(2210),
    /**
     * <code>S_GameStart = 2021;</code>
     */
    S_GameStart(2021),
    /**
     * <code>S_GameResult = 2022;</code>
     */
    S_GameResult(2022),
    /**
     * <code>S_EnterStage = 2023;</code>
     */
    S_EnterStage(2023),
    /**
     * <code>S_Timer = 2076;</code>
     */
    S_Timer(2076),
    /**
     * <code>C_ChooseSeat = 2025;</code>
     */
    C_ChooseSeat(2025),
    /**
     * <code>S_ChooseSeat = 2026;</code>
     */
    S_ChooseSeat(2026),
    /**
     * <code>C_ConfirmUseAbility = 2027;</code>
     */
    C_ConfirmUseAbility(2027),
    /**
     * <code>S_TargetResult = 2028;</code>
     */
    S_TargetResult(2028),
    /**
     * <code>S_RoleActionEnd = 2029;</code>
     */
    S_RoleActionEnd(2029),
    /**
     * <code>S_RoleUseAbility = 2030;</code>
     */
    S_RoleUseAbility(2030),
    /**
     * <code>S_Werewolves = 2031;</code>
     */
    S_Werewolves(2031),
    /**
     * <code>S_WerewolvesActionResult = 2032;</code>
     */
    S_WerewolvesActionResult(2032),
    /**
     * <code>S_SeerActionResult = 2033;</code>
     */
    S_SeerActionResult(2033),
    /**
     * <code>S_StartSpeakFrom = 2077;</code>
     */
    S_StartSpeakFrom(2077),
    /**
     * <code>S_TurnSpeak = 2036;</code>
     */
    S_TurnSpeak(2036),
    /**
     * <code>C_EndSpeak = 2037;</code>
     */
    C_EndSpeak(2037),
    /**
     * <code>S_EndSpeak = 2040;</code>
     */
    S_EndSpeak(2040),
    /**
     * <code>S_AllSpeakEnd = 2078;</code>
     */
    S_AllSpeakEnd(2078),
    /**
     * <code>S_VoteResult = 2038;</code>
     */
    S_VoteResult(2038),
    /**
     * <code>S_Death = 2039;</code>
     */
    S_Death(2039),
    /**
     * <code>S_SyncGameState = 2060;</code>
     */
    S_SyncGameState(2060),
    /**
     * <code>S_SyncSeerState = 2061;</code>
     */
    S_SyncSeerState(2061),
    /**
     * <code>S_SyncWitchState = 2062;</code>
     */
    S_SyncWitchState(2062),
    /**
     * <code>S_SyncDefenderState = 2063;</code>
     */
    S_SyncDefenderState(2063),
    /**
     * <code>S_SyncStage = 2064;</code>
     */
    S_SyncStage(2064),
    /**
     * <code>S_SyncGameStageRecords = 2065;</code>
     */
    S_SyncGameStageRecords(2065),
    /**
     * <code>S_RunForSheriff = 2068;</code>
     */
    S_RunForSheriff(2068),
    /**
     * <code>C_QuitSheriff = 2069;</code>
     */
    C_QuitSheriff(2069),
    /**
     * <code>S_QuitSheriff = 2070;</code>
     */
    S_QuitSheriff(2070),
    /**
     * <code>S_SheriffResult = 2071;</code>
     */
    S_SheriffResult(2071),
    /**
     * <code>S_SheriffActionResult = 2072;</code>
     */
    S_SheriffActionResult(2072),
    /**
     * <code>S_SheriffChooseSpeakFrom = 2073;</code>
     */
    S_SheriffChooseSpeakFrom(2073),
    /**
     * <code>C_WerewolfExpose = 2074;</code>
     */
    C_WerewolfExpose(2074),
    /**
     * <code>C_ConfirmResult = 2075;</code>
     */
    C_ConfirmResult(2075),
    /**
     * <code>C_EnableCurSpeakInterrupt = 2079;</code>
     */
    C_EnableCurSpeakInterrupt(2079),
    /**
     * <code>S_EnableCurSpeakInterrupt = 2080;</code>
     */
    S_EnableCurSpeakInterrupt(2080),
    /**
     * <code>S_SelfRole = 2081;</code>
     */
    S_SelfRole(2081),
    /**
     * <code>S_TargetRole = 2082;</code>
     */
    S_TargetRole(2082),
    /**
     * <code>S_SyncONTroubleMakerState = 2083;</code>
     */
    S_SyncONTroubleMakerState(2083),
    /**
     * <code>ROUTER_GAME_END = 2999;</code>
     */
    ROUTER_GAME_END(2999),
    /**
     * <code>ROUTER_KITSVR_BEGIN = 3000;</code>
     */
    ROUTER_KITSVR_BEGIN(3000),
    /**
     * <code>C_ReqUserNetEaseToken = 3001;</code>
     */
    C_ReqUserNetEaseToken(3001),
    /**
     * <code>S_RespUserNetEaseToken = 3002;</code>
     */
    S_RespUserNetEaseToken(3002),
    /**
     * <code>C_ReqRankData = 3003;</code>
     */
    C_ReqRankData(3003),
    /**
     * <code>S_RespRankData = 3004;</code>
     */
    S_RespRankData(3004),
    /**
     * <code>C_ReqNewMail = 3005;</code>
     */
    C_ReqNewMail(3005),
    /**
     * <code>S_RespNewMail = 3006;</code>
     */
    S_RespNewMail(3006),
    /**
     * <code>C_ReportGetNewMail = 3007;</code>
     */
    C_ReportGetNewMail(3007),
    /**
     * <code>C_ReqFindUserByName = 3008;</code>
     */
    C_ReqFindUserByName(3008),
    /**
     * <code>S_ResFindUserByName = 3009;</code>
     */
    S_ResFindUserByName(3009),
    /**
     * <code>C_ReqMatchRankData = 3010;</code>
     */
    C_ReqMatchRankData(3010),
    /**
     * <code>S_RespMatchRankData = 3011;</code>
     */
    S_RespMatchRankData(3011),
    /**
     * <code>C_ReqGetAttachment = 3012;</code>
     */
    C_ReqGetAttachment(3012),
    /**
     * <code>S_RespGetAttachment = 3013;</code>
     */
    S_RespGetAttachment(3013),
    /**
     * <code>C_ReqUserSnapshot = 3014;</code>
     */
    C_ReqUserSnapshot(3014),
    /**
     * <code>S_RespUserSnapshot = 3015;</code>
     */
    S_RespUserSnapshot(3015),
    /**
     * <code>C_ReqBatchUserSnapshot = 3016;</code>
     */
    C_ReqBatchUserSnapshot(3016),
    /**
     * <code>S_RespBatchUserSnapshot = 3017;</code>
     */
    S_RespBatchUserSnapshot(3017),
    /**
     * <code>C_ReqUserDetail = 3018;</code>
     */
    C_ReqUserDetail(3018),
    /**
     * <code>S_RespUserDetail = 3019;</code>
     */
    S_RespUserDetail(3019),
    /**
     * <code>C_ReqMatchHonor = 3020;</code>
     */
    C_ReqMatchHonor(3020),
    /**
     * <code>S_RespMatchHonor = 3021;</code>
     */
    S_RespMatchHonor(3021),
    /**
     * <code>ROUTER_KITSVR_END = 3999;</code>
     */
    ROUTER_KITSVR_END(3999),
    /**
     * <code>ROUTER_CLUB_BEGIN = 4000;</code>
     */
    ROUTER_CLUB_BEGIN(4000),
    /**
     * <code>C_ReqMyClubs = 4001;</code>
     */
    C_ReqMyClubs(4001),
    /**
     * <code>S_RespMyClubs = 4002;</code>
     */
    S_RespMyClubs(4002),
    /**
     * <code>C_ReqClubDetail = 4003;</code>
     */
    C_ReqClubDetail(4003),
    /**
     * <code>S_RespClubDetail = 4004;</code>
     */
    S_RespClubDetail(4004),
    /**
     * <code>C_ReqClubMembers = 4005;</code>
     */
    C_ReqClubMembers(4005),
    /**
     * <code>S_RespClubMembers = 4006;</code>
     */
    S_RespClubMembers(4006),
    /**
     * <code>C_ReqClubMembersOnlineStatus = 4007;</code>
     */
    C_ReqClubMembersOnlineStatus(4007),
    /**
     * <code>S_RespClubMembersOnlineStatus = 4008;</code>
     */
    S_RespClubMembersOnlineStatus(4008),
    /**
     * <code>C_ReqTopClubs = 4009;</code>
     */
    C_ReqTopClubs(4009),
    /**
     * <code>S_RespTopClubs = 4010;</code>
     */
    S_RespTopClubs(4010),
    /**
     * <code>C_ReqCreateClub = 4011;</code>
     */
    C_ReqCreateClub(4011),
    /**
     * <code>S_RespCreateClub = 4012;</code>
     */
    S_RespCreateClub(4012),
    /**
     * <code>C_ReqApplyJoinClub = 4013;</code>
     */
    C_ReqApplyJoinClub(4013),
    /**
     * <code>S_RespApplyJoinClub = 4014;</code>
     */
    S_RespApplyJoinClub(4014),
    /**
     * <code>C_ReqConfirmApplyJoinClub = 4015;</code>
     */
    C_ReqConfirmApplyJoinClub(4015),
    /**
     * <code>S_RespConfirmApplyJoinClub = 4016;</code>
     */
    S_RespConfirmApplyJoinClub(4016),
    /**
     * <code>S_NoticeApplyJoinClubResult = 4017;</code>
     */
    S_NoticeApplyJoinClubResult(4017),
    /**
     * <code>C_ReqListApplyJoinClub = 4018;</code>
     */
    C_ReqListApplyJoinClub(4018),
    /**
     * <code>S_RespListApplyJoinClub = 4019;</code>
     */
    S_RespListApplyJoinClub(4019),
    /**
     * <code>S_NoticeNewApplyJoinClub = 4020;</code>
     */
    S_NoticeNewApplyJoinClub(4020),
    /**
     * <code>C_ReqQuitClub = 4021;</code>
     */
    C_ReqQuitClub(4021),
    /**
     * <code>S_RespQuitClub = 4022;</code>
     */
    S_RespQuitClub(4022),
    /**
     * <code>S_NoticeClubEvent = 4023;</code>
     */
    S_NoticeClubEvent(4023),
    /**
     * <code>C_SendMessageInClub = 4024;</code>
     */
    C_SendMessageInClub(4024),
    /**
     * <code>S_NoticeClubUserMessage = 4025;</code>
     */
    S_NoticeClubUserMessage(4025),
    /**
     * <code>C_ReqDisbandClub = 4026;</code>
     */
    C_ReqDisbandClub(4026),
    /**
     * <code>S_RespDisbandClub = 4027;</code>
     */
    S_RespDisbandClub(4027),
    /**
     * <code>C_ReqChangeClubMemberJob = 4028;</code>
     */
    C_ReqChangeClubMemberJob(4028),
    /**
     * <code>S_RespChangeClubMemberJob = 4029;</code>
     */
    S_RespChangeClubMemberJob(4029),
    /**
     * <code>C_ReqChangeClubAnnouncement = 4030;</code>
     */
    C_ReqChangeClubAnnouncement(4030),
    /**
     * <code>S_RespChangeClubAnnouncement = 4031;</code>
     */
    S_RespChangeClubAnnouncement(4031),
    /**
     * <code>C_ReqClubMemberRooms = 4032;</code>
     */
    C_ReqClubMemberRooms(4032),
    /**
     * <code>S_RespClubMemberRooms = 4033;</code>
     */
    S_RespClubMemberRooms(4033),
    /**
     * <code>C_ReqFindClubByName = 4034;</code>
     */
    C_ReqFindClubByName(4034),
    /**
     * <code>S_RespFindClubByName = 4035;</code>
     */
    S_RespFindClubByName(4035),
    /**
     * <code>C_ReqKickClubMember = 4036;</code>
     */
    C_ReqKickClubMember(4036),
    /**
     * <code>S_RespKickClubMember = 4037;</code>
     */
    S_RespKickClubMember(4037),
    /**
     * <code>ROUTER_CLUB_END = 4999;</code>
     */
    ROUTER_CLUB_END(4999),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ClientInvaildOpCode = 0;</code>
     */
    public static final int ClientInvaildOpCode_VALUE = 0;
    /**
     * <pre>
     * gate需要解析的协议
     * </pre>
     *
     * <code>ReqHeartBeat = 1;</code>
     */
    public static final int ReqHeartBeat_VALUE = 1;
    /**
     * <code>RespHeartBeat = 2;</code>
     */
    public static final int RespHeartBeat_VALUE = 2;
    /**
     * <code>ReqLogin = 3;</code>
     */
    public static final int ReqLogin_VALUE = 3;
    /**
     * <code>RespLogin = 4;</code>
     */
    public static final int RespLogin_VALUE = 4;
    /**
     * <pre>
     * 客户端请求退出
     * </pre>
     *
     * <code>ReqLogout = 5;</code>
     */
    public static final int ReqLogout_VALUE = 5;
    /**
     * <pre>
     * 服务器踢人
     * </pre>
     *
     * <code>NoticeLogout = 6;</code>
     */
    public static final int NoticeLogout_VALUE = 6;
    /**
     * <code>S_MessageInChannel = 11;</code>
     */
    public static final int S_MessageInChannel_VALUE = 11;
    /**
     * <code>ROUTE_ENTITY_BEGIN = 200;</code>
     */
    public static final int ROUTE_ENTITY_BEGIN_VALUE = 200;
    /**
     * <code>C_ReqUserData = 201;</code>
     */
    public static final int C_ReqUserData_VALUE = 201;
    /**
     * <code>S_RespUserData = 202;</code>
     */
    public static final int S_RespUserData_VALUE = 202;
    /**
     * <code>C_ReqInitUserData = 203;</code>
     */
    public static final int C_ReqInitUserData_VALUE = 203;
    /**
     * <code>S_RespInitUserData = 204;</code>
     */
    public static final int S_RespInitUserData_VALUE = 204;
    /**
     * <code>C_ReqChangeAvatar = 205;</code>
     */
    public static final int C_ReqChangeAvatar_VALUE = 205;
    /**
     * <code>S_ResChangeAvatar = 206;</code>
     */
    public static final int S_ResChangeAvatar_VALUE = 206;
    /**
     * <code>C_ReqGameRecords = 210;</code>
     */
    public static final int C_ReqGameRecords_VALUE = 210;
    /**
     * <code>S_RespGameRecords = 211;</code>
     */
    public static final int S_RespGameRecords_VALUE = 211;
    /**
     * <code>S_NoticeUserExpLevel = 212;</code>
     */
    public static final int S_NoticeUserExpLevel_VALUE = 212;
    /**
     * <code>C_ReqBindAccount = 213;</code>
     */
    public static final int C_ReqBindAccount_VALUE = 213;
    /**
     * <code>S_RespBindAccount = 214;</code>
     */
    public static final int S_RespBindAccount_VALUE = 214;
    /**
     * <code>C_ReqUserMatchData = 215;</code>
     */
    public static final int C_ReqUserMatchData_VALUE = 215;
    /**
     * <code>S_RespUserMatchData = 216;</code>
     */
    public static final int S_RespUserMatchData_VALUE = 216;
    /**
     * <code>C_ReqUserMatchGameRecords = 217;</code>
     */
    public static final int C_ReqUserMatchGameRecords_VALUE = 217;
    /**
     * <code>S_RespUserMatchGameRecords = 218;</code>
     */
    public static final int S_RespUserMatchGameRecords_VALUE = 218;
    /**
     * <code>C_ReqGoodsByCategory = 219;</code>
     */
    public static final int C_ReqGoodsByCategory_VALUE = 219;
    /**
     * <code>S_RespGoodsByCategory = 220;</code>
     */
    public static final int S_RespGoodsByCategory_VALUE = 220;
    /**
     * <code>C_ReqAllGoods = 221;</code>
     */
    public static final int C_ReqAllGoods_VALUE = 221;
    /**
     * <code>S_RespAllGoods = 222;</code>
     */
    public static final int S_RespAllGoods_VALUE = 222;
    /**
     * <code>C_ReqAllTasks = 223;</code>
     */
    public static final int C_ReqAllTasks_VALUE = 223;
    /**
     * <code>S_RespAllTasks = 224;</code>
     */
    public static final int S_RespAllTasks_VALUE = 224;
    /**
     * <code>S_NtfTaskState = 225;</code>
     */
    public static final int S_NtfTaskState_VALUE = 225;
    /**
     * <code>C_ReqChangeTask = 226;</code>
     */
    public static final int C_ReqChangeTask_VALUE = 226;
    /**
     * <code>S_RespChangeTask = 227;</code>
     */
    public static final int S_RespChangeTask_VALUE = 227;
    /**
     * <code>C_ReqMyActivity = 228;</code>
     */
    public static final int C_ReqMyActivity_VALUE = 228;
    /**
     * <code>S_RespMyActivity = 229;</code>
     */
    public static final int S_RespMyActivity_VALUE = 229;
    /**
     * <code>C_ReqEditSignature = 230;</code>
     */
    public static final int C_ReqEditSignature_VALUE = 230;
    /**
     * <code>S_RespEditSignature = 231;</code>
     */
    public static final int S_RespEditSignature_VALUE = 231;
    /**
     * <code>C_ReqUpLoadFigure = 232;</code>
     */
    public static final int C_ReqUpLoadFigure_VALUE = 232;
    /**
     * <code>S_RespUpLoadFigure = 233;</code>
     */
    public static final int S_RespUpLoadFigure_VALUE = 233;
    /**
     * <code>ROUTE_ENTITY_END = 999;</code>
     */
    public static final int ROUTE_ENTITY_END_VALUE = 999;
    /**
     * <code>ROUTER_LOBBY_BEGIN = 1000;</code>
     */
    public static final int ROUTER_LOBBY_BEGIN_VALUE = 1000;
    /**
     * <code>C_ReqQuickJoinRoom = 1001;</code>
     */
    public static final int C_ReqQuickJoinRoom_VALUE = 1001;
    /**
     * <code>C_ReqJoinRoom = 1027;</code>
     */
    public static final int C_ReqJoinRoom_VALUE = 1027;
    /**
     * <code>S_RespJoinRoom = 1002;</code>
     */
    public static final int S_RespJoinRoom_VALUE = 1002;
    /**
     * <code>C_ReqQuitRoom = 1003;</code>
     */
    public static final int C_ReqQuitRoom_VALUE = 1003;
    /**
     * <code>S_RespQuitRoom = 1004;</code>
     */
    public static final int S_RespQuitRoom_VALUE = 1004;
    /**
     * <code>C_ReqCreateRoom = 1028;</code>
     */
    public static final int C_ReqCreateRoom_VALUE = 1028;
    /**
     * <code>S_RespCreateRoom = 1029;</code>
     */
    public static final int S_RespCreateRoom_VALUE = 1029;
    /**
     * <code>C_ReqApplyAddFriend = 1008;</code>
     */
    public static final int C_ReqApplyAddFriend_VALUE = 1008;
    /**
     * <code>S_ResApplyAddFriend = 1009;</code>
     */
    public static final int S_ResApplyAddFriend_VALUE = 1009;
    /**
     * <code>C_ReqConfirmAddFriend = 1010;</code>
     */
    public static final int C_ReqConfirmAddFriend_VALUE = 1010;
    /**
     * <code>S_ResConfirmAddFriend = 1011;</code>
     */
    public static final int S_ResConfirmAddFriend_VALUE = 1011;
    /**
     * <code>C_ReqDelFriend = 1012;</code>
     */
    public static final int C_ReqDelFriend_VALUE = 1012;
    /**
     * <code>S_ResDelFriend = 1013;</code>
     */
    public static final int S_ResDelFriend_VALUE = 1013;
    /**
     * <code>C_ReqFriendChat = 1014;</code>
     */
    public static final int C_ReqFriendChat_VALUE = 1014;
    /**
     * <code>S_ResFriendChat = 1015;</code>
     */
    public static final int S_ResFriendChat_VALUE = 1015;
    /**
     * <code>C_ReqFollowFriend = 1016;</code>
     */
    public static final int C_ReqFollowFriend_VALUE = 1016;
    /**
     * <code>S_ResFollowFriend = 1017;</code>
     */
    public static final int S_ResFollowFriend_VALUE = 1017;
    /**
     * <code>C_ReqFriendData = 1018;</code>
     */
    public static final int C_ReqFriendData_VALUE = 1018;
    /**
     * <code>S_ResFriendData = 1019;</code>
     */
    public static final int S_ResFriendData_VALUE = 1019;
    /**
     * <code>C_ReqFriendList = 1020;</code>
     */
    public static final int C_ReqFriendList_VALUE = 1020;
    /**
     * <code>S_ResFriendList = 1021;</code>
     */
    public static final int S_ResFriendList_VALUE = 1021;
    /**
     * <code>S_NoticeApplyAddFriend = 1022;</code>
     */
    public static final int S_NoticeApplyAddFriend_VALUE = 1022;
    /**
     * <code>S_NoticeConfirmAddFriend = 1023;</code>
     */
    public static final int S_NoticeConfirmAddFriend_VALUE = 1023;
    /**
     * <code>S_NoticeDelFriend = 1024;</code>
     */
    public static final int S_NoticeDelFriend_VALUE = 1024;
    /**
     * <code>C_ReqFriendStatus = 1025;</code>
     */
    public static final int C_ReqFriendStatus_VALUE = 1025;
    /**
     * <code>S_ResFriendStatus = 1026;</code>
     */
    public static final int S_ResFriendStatus_VALUE = 1026;
    /**
     * <code>C_InviteJoinRoom = 1030;</code>
     */
    public static final int C_InviteJoinRoom_VALUE = 1030;
    /**
     * <code>S_InviteJoinRoomResult = 1031;</code>
     */
    public static final int S_InviteJoinRoomResult_VALUE = 1031;
    /**
     * <code>S_NoticeInviteToJoinRoom = 1032;</code>
     */
    public static final int S_NoticeInviteToJoinRoom_VALUE = 1032;
    /**
     * <code>S_NoticeGameFreeze = 1033;</code>
     */
    public static final int S_NoticeGameFreeze_VALUE = 1033;
    /**
     * <code>C_ReqJoinMatch = 1035;</code>
     */
    public static final int C_ReqJoinMatch_VALUE = 1035;
    /**
     * <code>S_RespJoinMatch = 1036;</code>
     */
    public static final int S_RespJoinMatch_VALUE = 1036;
    /**
     * <code>C_ReqCancelMatch = 1037;</code>
     */
    public static final int C_ReqCancelMatch_VALUE = 1037;
    /**
     * <code>S_RespCancelMatch = 1038;</code>
     */
    public static final int S_RespCancelMatch_VALUE = 1038;
    /**
     * <code>C_ReqUserSignUpMatch = 1039;</code>
     */
    public static final int C_ReqUserSignUpMatch_VALUE = 1039;
    /**
     * <code>S_RespUserSignUpMatch = 1040;</code>
     */
    public static final int S_RespUserSignUpMatch_VALUE = 1040;
    /**
     * <code>C_ReqJoinChatChannel = 1041;</code>
     */
    public static final int C_ReqJoinChatChannel_VALUE = 1041;
    /**
     * <code>S_RespJoinChatChannel = 1042;</code>
     */
    public static final int S_RespJoinChatChannel_VALUE = 1042;
    /**
     * <code>C_ReqChatChannelList = 1043;</code>
     */
    public static final int C_ReqChatChannelList_VALUE = 1043;
    /**
     * <code>S_RespChatChannelList = 1044;</code>
     */
    public static final int S_RespChatChannelList_VALUE = 1044;
    /**
     * <code>C_SendMessageInChannel = 1045;</code>
     */
    public static final int C_SendMessageInChannel_VALUE = 1045;
    /**
     * <code>C_ReqQuitChatChannel = 1046;</code>
     */
    public static final int C_ReqQuitChatChannel_VALUE = 1046;
    /**
     * <code>S_RespQuitChatChannel = 1047;</code>
     */
    public static final int S_RespQuitChatChannel_VALUE = 1047;
    /**
     * <code>C_ReqCreateMatchRoom = 1048;</code>
     */
    public static final int C_ReqCreateMatchRoom_VALUE = 1048;
    /**
     * <code>S_RespCreateMatchRoom = 1049;</code>
     */
    public static final int S_RespCreateMatchRoom_VALUE = 1049;
    /**
     * <code>C_ReqJoinMatchRoom = 1050;</code>
     */
    public static final int C_ReqJoinMatchRoom_VALUE = 1050;
    /**
     * <code>S_RespJoinMatchRoom = 1051;</code>
     */
    public static final int S_RespJoinMatchRoom_VALUE = 1051;
    /**
     * <code>ROUTER_LOBBY_END = 1999;</code>
     */
    public static final int ROUTER_LOBBY_END_VALUE = 1999;
    /**
     * <code>ROUTER_GAME_BEGIN = 2000;</code>
     */
    public static final int ROUTER_GAME_BEGIN_VALUE = 2000;
    /**
     * <code>C_ReportClientReadyForGame = 2001;</code>
     */
    public static final int C_ReportClientReadyForGame_VALUE = 2001;
    /**
     * <code>C_ReqReady = 2002;</code>
     */
    public static final int C_ReqReady_VALUE = 2002;
    /**
     * <code>S_RespReady = 2003;</code>
     */
    public static final int S_RespReady_VALUE = 2003;
    /**
     * <code>C_ReqCancelReady = 2004;</code>
     */
    public static final int C_ReqCancelReady_VALUE = 2004;
    /**
     * <code>S_RespCancelReady = 2005;</code>
     */
    public static final int S_RespCancelReady_VALUE = 2005;
    /**
     * <code>C_ReqRoomStartGame = 2006;</code>
     */
    public static final int C_ReqRoomStartGame_VALUE = 2006;
    /**
     * <code>S_RespRoomStartGame = 2007;</code>
     */
    public static final int S_RespRoomStartGame_VALUE = 2007;
    /**
     * <code>S_IsRoomAbleStartGame = 2020;</code>
     */
    public static final int S_IsRoomAbleStartGame_VALUE = 2020;
    /**
     * <code>C_ReqKickUser = 2008;</code>
     */
    public static final int C_ReqKickUser_VALUE = 2008;
    /**
     * <code>S_RespKickUser = 2009;</code>
     */
    public static final int S_RespKickUser_VALUE = 2009;
    /**
     * <code>S_NoticeBeKicked = 2010;</code>
     */
    public static final int S_NoticeBeKicked_VALUE = 2010;
    /**
     * <code>S_SyncRoomState = 2011;</code>
     */
    public static final int S_SyncRoomState_VALUE = 2011;
    /**
     * <code>S_UserJoin = 2012;</code>
     */
    public static final int S_UserJoin_VALUE = 2012;
    /**
     * <code>S_UserQuit = 2013;</code>
     */
    public static final int S_UserQuit_VALUE = 2013;
    /**
     * <code>S_UserReady = 2014;</code>
     */
    public static final int S_UserReady_VALUE = 2014;
    /**
     * <code>S_UserConnect = 2015;</code>
     */
    public static final int S_UserConnect_VALUE = 2015;
    /**
     * <code>C_ReportUserLeaveState = 2034;</code>
     */
    public static final int C_ReportUserLeaveState_VALUE = 2034;
    /**
     * <code>S_NewRoomOwner = 2016;</code>
     */
    public static final int S_NewRoomOwner_VALUE = 2016;
    /**
     * <code>C_SendMessageInRoom = 2017;</code>
     */
    public static final int C_SendMessageInRoom_VALUE = 2017;
    /**
     * <code>S_UserMessageInRoom = 2018;</code>
     */
    public static final int S_UserMessageInRoom_VALUE = 2018;
    /**
     * <code>S_GameSyncOK = 2019;</code>
     */
    public static final int S_GameSyncOK_VALUE = 2019;
    /**
     * <code>C_RoomSettingEnableSpeakInterrupt = 2200;</code>
     */
    public static final int C_RoomSettingEnableSpeakInterrupt_VALUE = 2200;
    /**
     * <code>S_RoomSettingEnableSpeakInterrupt = 2201;</code>
     */
    public static final int S_RoomSettingEnableSpeakInterrupt_VALUE = 2201;
    /**
     * <code>C_RoomSettingUserLevelLimit = 2202;</code>
     */
    public static final int C_RoomSettingUserLevelLimit_VALUE = 2202;
    /**
     * <code>S_RoomSettingUserLevelLimit = 2203;</code>
     */
    public static final int S_RoomSettingUserLevelLimit_VALUE = 2203;
    /**
     * <code>C_RoomSettingPWD = 2204;</code>
     */
    public static final int C_RoomSettingPWD_VALUE = 2204;
    /**
     * <code>S_RoomSettingPWD = 2205;</code>
     */
    public static final int S_RoomSettingPWD_VALUE = 2205;
    /**
     * <code>C_RoomSettingEnableSpectate = 2206;</code>
     */
    public static final int C_RoomSettingEnableSpectate_VALUE = 2206;
    /**
     * <code>S_RoomSettingEnableSpectate = 2207;</code>
     */
    public static final int S_RoomSettingEnableSpectate_VALUE = 2207;
    /**
     * <code>C_ReqChangeSeat = 2208;</code>
     */
    public static final int C_ReqChangeSeat_VALUE = 2208;
    /**
     * <code>S_RespChangeSeat = 2209;</code>
     */
    public static final int S_RespChangeSeat_VALUE = 2209;
    /**
     * <code>S_UserChangeSeat = 2210;</code>
     */
    public static final int S_UserChangeSeat_VALUE = 2210;
    /**
     * <code>S_GameStart = 2021;</code>
     */
    public static final int S_GameStart_VALUE = 2021;
    /**
     * <code>S_GameResult = 2022;</code>
     */
    public static final int S_GameResult_VALUE = 2022;
    /**
     * <code>S_EnterStage = 2023;</code>
     */
    public static final int S_EnterStage_VALUE = 2023;
    /**
     * <code>S_Timer = 2076;</code>
     */
    public static final int S_Timer_VALUE = 2076;
    /**
     * <code>C_ChooseSeat = 2025;</code>
     */
    public static final int C_ChooseSeat_VALUE = 2025;
    /**
     * <code>S_ChooseSeat = 2026;</code>
     */
    public static final int S_ChooseSeat_VALUE = 2026;
    /**
     * <code>C_ConfirmUseAbility = 2027;</code>
     */
    public static final int C_ConfirmUseAbility_VALUE = 2027;
    /**
     * <code>S_TargetResult = 2028;</code>
     */
    public static final int S_TargetResult_VALUE = 2028;
    /**
     * <code>S_RoleActionEnd = 2029;</code>
     */
    public static final int S_RoleActionEnd_VALUE = 2029;
    /**
     * <code>S_RoleUseAbility = 2030;</code>
     */
    public static final int S_RoleUseAbility_VALUE = 2030;
    /**
     * <code>S_Werewolves = 2031;</code>
     */
    public static final int S_Werewolves_VALUE = 2031;
    /**
     * <code>S_WerewolvesActionResult = 2032;</code>
     */
    public static final int S_WerewolvesActionResult_VALUE = 2032;
    /**
     * <code>S_SeerActionResult = 2033;</code>
     */
    public static final int S_SeerActionResult_VALUE = 2033;
    /**
     * <code>S_StartSpeakFrom = 2077;</code>
     */
    public static final int S_StartSpeakFrom_VALUE = 2077;
    /**
     * <code>S_TurnSpeak = 2036;</code>
     */
    public static final int S_TurnSpeak_VALUE = 2036;
    /**
     * <code>C_EndSpeak = 2037;</code>
     */
    public static final int C_EndSpeak_VALUE = 2037;
    /**
     * <code>S_EndSpeak = 2040;</code>
     */
    public static final int S_EndSpeak_VALUE = 2040;
    /**
     * <code>S_AllSpeakEnd = 2078;</code>
     */
    public static final int S_AllSpeakEnd_VALUE = 2078;
    /**
     * <code>S_VoteResult = 2038;</code>
     */
    public static final int S_VoteResult_VALUE = 2038;
    /**
     * <code>S_Death = 2039;</code>
     */
    public static final int S_Death_VALUE = 2039;
    /**
     * <code>S_SyncGameState = 2060;</code>
     */
    public static final int S_SyncGameState_VALUE = 2060;
    /**
     * <code>S_SyncSeerState = 2061;</code>
     */
    public static final int S_SyncSeerState_VALUE = 2061;
    /**
     * <code>S_SyncWitchState = 2062;</code>
     */
    public static final int S_SyncWitchState_VALUE = 2062;
    /**
     * <code>S_SyncDefenderState = 2063;</code>
     */
    public static final int S_SyncDefenderState_VALUE = 2063;
    /**
     * <code>S_SyncStage = 2064;</code>
     */
    public static final int S_SyncStage_VALUE = 2064;
    /**
     * <code>S_SyncGameStageRecords = 2065;</code>
     */
    public static final int S_SyncGameStageRecords_VALUE = 2065;
    /**
     * <code>S_RunForSheriff = 2068;</code>
     */
    public static final int S_RunForSheriff_VALUE = 2068;
    /**
     * <code>C_QuitSheriff = 2069;</code>
     */
    public static final int C_QuitSheriff_VALUE = 2069;
    /**
     * <code>S_QuitSheriff = 2070;</code>
     */
    public static final int S_QuitSheriff_VALUE = 2070;
    /**
     * <code>S_SheriffResult = 2071;</code>
     */
    public static final int S_SheriffResult_VALUE = 2071;
    /**
     * <code>S_SheriffActionResult = 2072;</code>
     */
    public static final int S_SheriffActionResult_VALUE = 2072;
    /**
     * <code>S_SheriffChooseSpeakFrom = 2073;</code>
     */
    public static final int S_SheriffChooseSpeakFrom_VALUE = 2073;
    /**
     * <code>C_WerewolfExpose = 2074;</code>
     */
    public static final int C_WerewolfExpose_VALUE = 2074;
    /**
     * <code>C_ConfirmResult = 2075;</code>
     */
    public static final int C_ConfirmResult_VALUE = 2075;
    /**
     * <code>C_EnableCurSpeakInterrupt = 2079;</code>
     */
    public static final int C_EnableCurSpeakInterrupt_VALUE = 2079;
    /**
     * <code>S_EnableCurSpeakInterrupt = 2080;</code>
     */
    public static final int S_EnableCurSpeakInterrupt_VALUE = 2080;
    /**
     * <code>S_SelfRole = 2081;</code>
     */
    public static final int S_SelfRole_VALUE = 2081;
    /**
     * <code>S_TargetRole = 2082;</code>
     */
    public static final int S_TargetRole_VALUE = 2082;
    /**
     * <code>S_SyncONTroubleMakerState = 2083;</code>
     */
    public static final int S_SyncONTroubleMakerState_VALUE = 2083;
    /**
     * <code>ROUTER_GAME_END = 2999;</code>
     */
    public static final int ROUTER_GAME_END_VALUE = 2999;
    /**
     * <code>ROUTER_KITSVR_BEGIN = 3000;</code>
     */
    public static final int ROUTER_KITSVR_BEGIN_VALUE = 3000;
    /**
     * <code>C_ReqUserNetEaseToken = 3001;</code>
     */
    public static final int C_ReqUserNetEaseToken_VALUE = 3001;
    /**
     * <code>S_RespUserNetEaseToken = 3002;</code>
     */
    public static final int S_RespUserNetEaseToken_VALUE = 3002;
    /**
     * <code>C_ReqRankData = 3003;</code>
     */
    public static final int C_ReqRankData_VALUE = 3003;
    /**
     * <code>S_RespRankData = 3004;</code>
     */
    public static final int S_RespRankData_VALUE = 3004;
    /**
     * <code>C_ReqNewMail = 3005;</code>
     */
    public static final int C_ReqNewMail_VALUE = 3005;
    /**
     * <code>S_RespNewMail = 3006;</code>
     */
    public static final int S_RespNewMail_VALUE = 3006;
    /**
     * <code>C_ReportGetNewMail = 3007;</code>
     */
    public static final int C_ReportGetNewMail_VALUE = 3007;
    /**
     * <code>C_ReqFindUserByName = 3008;</code>
     */
    public static final int C_ReqFindUserByName_VALUE = 3008;
    /**
     * <code>S_ResFindUserByName = 3009;</code>
     */
    public static final int S_ResFindUserByName_VALUE = 3009;
    /**
     * <code>C_ReqMatchRankData = 3010;</code>
     */
    public static final int C_ReqMatchRankData_VALUE = 3010;
    /**
     * <code>S_RespMatchRankData = 3011;</code>
     */
    public static final int S_RespMatchRankData_VALUE = 3011;
    /**
     * <code>C_ReqGetAttachment = 3012;</code>
     */
    public static final int C_ReqGetAttachment_VALUE = 3012;
    /**
     * <code>S_RespGetAttachment = 3013;</code>
     */
    public static final int S_RespGetAttachment_VALUE = 3013;
    /**
     * <code>C_ReqUserSnapshot = 3014;</code>
     */
    public static final int C_ReqUserSnapshot_VALUE = 3014;
    /**
     * <code>S_RespUserSnapshot = 3015;</code>
     */
    public static final int S_RespUserSnapshot_VALUE = 3015;
    /**
     * <code>C_ReqBatchUserSnapshot = 3016;</code>
     */
    public static final int C_ReqBatchUserSnapshot_VALUE = 3016;
    /**
     * <code>S_RespBatchUserSnapshot = 3017;</code>
     */
    public static final int S_RespBatchUserSnapshot_VALUE = 3017;
    /**
     * <code>C_ReqUserDetail = 3018;</code>
     */
    public static final int C_ReqUserDetail_VALUE = 3018;
    /**
     * <code>S_RespUserDetail = 3019;</code>
     */
    public static final int S_RespUserDetail_VALUE = 3019;
    /**
     * <code>C_ReqMatchHonor = 3020;</code>
     */
    public static final int C_ReqMatchHonor_VALUE = 3020;
    /**
     * <code>S_RespMatchHonor = 3021;</code>
     */
    public static final int S_RespMatchHonor_VALUE = 3021;
    /**
     * <code>ROUTER_KITSVR_END = 3999;</code>
     */
    public static final int ROUTER_KITSVR_END_VALUE = 3999;
    /**
     * <code>ROUTER_CLUB_BEGIN = 4000;</code>
     */
    public static final int ROUTER_CLUB_BEGIN_VALUE = 4000;
    /**
     * <code>C_ReqMyClubs = 4001;</code>
     */
    public static final int C_ReqMyClubs_VALUE = 4001;
    /**
     * <code>S_RespMyClubs = 4002;</code>
     */
    public static final int S_RespMyClubs_VALUE = 4002;
    /**
     * <code>C_ReqClubDetail = 4003;</code>
     */
    public static final int C_ReqClubDetail_VALUE = 4003;
    /**
     * <code>S_RespClubDetail = 4004;</code>
     */
    public static final int S_RespClubDetail_VALUE = 4004;
    /**
     * <code>C_ReqClubMembers = 4005;</code>
     */
    public static final int C_ReqClubMembers_VALUE = 4005;
    /**
     * <code>S_RespClubMembers = 4006;</code>
     */
    public static final int S_RespClubMembers_VALUE = 4006;
    /**
     * <code>C_ReqClubMembersOnlineStatus = 4007;</code>
     */
    public static final int C_ReqClubMembersOnlineStatus_VALUE = 4007;
    /**
     * <code>S_RespClubMembersOnlineStatus = 4008;</code>
     */
    public static final int S_RespClubMembersOnlineStatus_VALUE = 4008;
    /**
     * <code>C_ReqTopClubs = 4009;</code>
     */
    public static final int C_ReqTopClubs_VALUE = 4009;
    /**
     * <code>S_RespTopClubs = 4010;</code>
     */
    public static final int S_RespTopClubs_VALUE = 4010;
    /**
     * <code>C_ReqCreateClub = 4011;</code>
     */
    public static final int C_ReqCreateClub_VALUE = 4011;
    /**
     * <code>S_RespCreateClub = 4012;</code>
     */
    public static final int S_RespCreateClub_VALUE = 4012;
    /**
     * <code>C_ReqApplyJoinClub = 4013;</code>
     */
    public static final int C_ReqApplyJoinClub_VALUE = 4013;
    /**
     * <code>S_RespApplyJoinClub = 4014;</code>
     */
    public static final int S_RespApplyJoinClub_VALUE = 4014;
    /**
     * <code>C_ReqConfirmApplyJoinClub = 4015;</code>
     */
    public static final int C_ReqConfirmApplyJoinClub_VALUE = 4015;
    /**
     * <code>S_RespConfirmApplyJoinClub = 4016;</code>
     */
    public static final int S_RespConfirmApplyJoinClub_VALUE = 4016;
    /**
     * <code>S_NoticeApplyJoinClubResult = 4017;</code>
     */
    public static final int S_NoticeApplyJoinClubResult_VALUE = 4017;
    /**
     * <code>C_ReqListApplyJoinClub = 4018;</code>
     */
    public static final int C_ReqListApplyJoinClub_VALUE = 4018;
    /**
     * <code>S_RespListApplyJoinClub = 4019;</code>
     */
    public static final int S_RespListApplyJoinClub_VALUE = 4019;
    /**
     * <code>S_NoticeNewApplyJoinClub = 4020;</code>
     */
    public static final int S_NoticeNewApplyJoinClub_VALUE = 4020;
    /**
     * <code>C_ReqQuitClub = 4021;</code>
     */
    public static final int C_ReqQuitClub_VALUE = 4021;
    /**
     * <code>S_RespQuitClub = 4022;</code>
     */
    public static final int S_RespQuitClub_VALUE = 4022;
    /**
     * <code>S_NoticeClubEvent = 4023;</code>
     */
    public static final int S_NoticeClubEvent_VALUE = 4023;
    /**
     * <code>C_SendMessageInClub = 4024;</code>
     */
    public static final int C_SendMessageInClub_VALUE = 4024;
    /**
     * <code>S_NoticeClubUserMessage = 4025;</code>
     */
    public static final int S_NoticeClubUserMessage_VALUE = 4025;
    /**
     * <code>C_ReqDisbandClub = 4026;</code>
     */
    public static final int C_ReqDisbandClub_VALUE = 4026;
    /**
     * <code>S_RespDisbandClub = 4027;</code>
     */
    public static final int S_RespDisbandClub_VALUE = 4027;
    /**
     * <code>C_ReqChangeClubMemberJob = 4028;</code>
     */
    public static final int C_ReqChangeClubMemberJob_VALUE = 4028;
    /**
     * <code>S_RespChangeClubMemberJob = 4029;</code>
     */
    public static final int S_RespChangeClubMemberJob_VALUE = 4029;
    /**
     * <code>C_ReqChangeClubAnnouncement = 4030;</code>
     */
    public static final int C_ReqChangeClubAnnouncement_VALUE = 4030;
    /**
     * <code>S_RespChangeClubAnnouncement = 4031;</code>
     */
    public static final int S_RespChangeClubAnnouncement_VALUE = 4031;
    /**
     * <code>C_ReqClubMemberRooms = 4032;</code>
     */
    public static final int C_ReqClubMemberRooms_VALUE = 4032;
    /**
     * <code>S_RespClubMemberRooms = 4033;</code>
     */
    public static final int S_RespClubMemberRooms_VALUE = 4033;
    /**
     * <code>C_ReqFindClubByName = 4034;</code>
     */
    public static final int C_ReqFindClubByName_VALUE = 4034;
    /**
     * <code>S_RespFindClubByName = 4035;</code>
     */
    public static final int S_RespFindClubByName_VALUE = 4035;
    /**
     * <code>C_ReqKickClubMember = 4036;</code>
     */
    public static final int C_ReqKickClubMember_VALUE = 4036;
    /**
     * <code>S_RespKickClubMember = 4037;</code>
     */
    public static final int S_RespKickClubMember_VALUE = 4037;
    /**
     * <code>ROUTER_CLUB_END = 4999;</code>
     */
    public static final int ROUTER_CLUB_END_VALUE = 4999;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Client valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Client forNumber(int value) {
      switch (value) {
        case 0: return ClientInvaildOpCode;
        case 1: return ReqHeartBeat;
        case 2: return RespHeartBeat;
        case 3: return ReqLogin;
        case 4: return RespLogin;
        case 5: return ReqLogout;
        case 6: return NoticeLogout;
        case 11: return S_MessageInChannel;
        case 200: return ROUTE_ENTITY_BEGIN;
        case 201: return C_ReqUserData;
        case 202: return S_RespUserData;
        case 203: return C_ReqInitUserData;
        case 204: return S_RespInitUserData;
        case 205: return C_ReqChangeAvatar;
        case 206: return S_ResChangeAvatar;
        case 210: return C_ReqGameRecords;
        case 211: return S_RespGameRecords;
        case 212: return S_NoticeUserExpLevel;
        case 213: return C_ReqBindAccount;
        case 214: return S_RespBindAccount;
        case 215: return C_ReqUserMatchData;
        case 216: return S_RespUserMatchData;
        case 217: return C_ReqUserMatchGameRecords;
        case 218: return S_RespUserMatchGameRecords;
        case 219: return C_ReqGoodsByCategory;
        case 220: return S_RespGoodsByCategory;
        case 221: return C_ReqAllGoods;
        case 222: return S_RespAllGoods;
        case 223: return C_ReqAllTasks;
        case 224: return S_RespAllTasks;
        case 225: return S_NtfTaskState;
        case 226: return C_ReqChangeTask;
        case 227: return S_RespChangeTask;
        case 228: return C_ReqMyActivity;
        case 229: return S_RespMyActivity;
        case 230: return C_ReqEditSignature;
        case 231: return S_RespEditSignature;
        case 232: return C_ReqUpLoadFigure;
        case 233: return S_RespUpLoadFigure;
        case 999: return ROUTE_ENTITY_END;
        case 1000: return ROUTER_LOBBY_BEGIN;
        case 1001: return C_ReqQuickJoinRoom;
        case 1027: return C_ReqJoinRoom;
        case 1002: return S_RespJoinRoom;
        case 1003: return C_ReqQuitRoom;
        case 1004: return S_RespQuitRoom;
        case 1028: return C_ReqCreateRoom;
        case 1029: return S_RespCreateRoom;
        case 1008: return C_ReqApplyAddFriend;
        case 1009: return S_ResApplyAddFriend;
        case 1010: return C_ReqConfirmAddFriend;
        case 1011: return S_ResConfirmAddFriend;
        case 1012: return C_ReqDelFriend;
        case 1013: return S_ResDelFriend;
        case 1014: return C_ReqFriendChat;
        case 1015: return S_ResFriendChat;
        case 1016: return C_ReqFollowFriend;
        case 1017: return S_ResFollowFriend;
        case 1018: return C_ReqFriendData;
        case 1019: return S_ResFriendData;
        case 1020: return C_ReqFriendList;
        case 1021: return S_ResFriendList;
        case 1022: return S_NoticeApplyAddFriend;
        case 1023: return S_NoticeConfirmAddFriend;
        case 1024: return S_NoticeDelFriend;
        case 1025: return C_ReqFriendStatus;
        case 1026: return S_ResFriendStatus;
        case 1030: return C_InviteJoinRoom;
        case 1031: return S_InviteJoinRoomResult;
        case 1032: return S_NoticeInviteToJoinRoom;
        case 1033: return S_NoticeGameFreeze;
        case 1035: return C_ReqJoinMatch;
        case 1036: return S_RespJoinMatch;
        case 1037: return C_ReqCancelMatch;
        case 1038: return S_RespCancelMatch;
        case 1039: return C_ReqUserSignUpMatch;
        case 1040: return S_RespUserSignUpMatch;
        case 1041: return C_ReqJoinChatChannel;
        case 1042: return S_RespJoinChatChannel;
        case 1043: return C_ReqChatChannelList;
        case 1044: return S_RespChatChannelList;
        case 1045: return C_SendMessageInChannel;
        case 1046: return C_ReqQuitChatChannel;
        case 1047: return S_RespQuitChatChannel;
        case 1048: return C_ReqCreateMatchRoom;
        case 1049: return S_RespCreateMatchRoom;
        case 1050: return C_ReqJoinMatchRoom;
        case 1051: return S_RespJoinMatchRoom;
        case 1999: return ROUTER_LOBBY_END;
        case 2000: return ROUTER_GAME_BEGIN;
        case 2001: return C_ReportClientReadyForGame;
        case 2002: return C_ReqReady;
        case 2003: return S_RespReady;
        case 2004: return C_ReqCancelReady;
        case 2005: return S_RespCancelReady;
        case 2006: return C_ReqRoomStartGame;
        case 2007: return S_RespRoomStartGame;
        case 2020: return S_IsRoomAbleStartGame;
        case 2008: return C_ReqKickUser;
        case 2009: return S_RespKickUser;
        case 2010: return S_NoticeBeKicked;
        case 2011: return S_SyncRoomState;
        case 2012: return S_UserJoin;
        case 2013: return S_UserQuit;
        case 2014: return S_UserReady;
        case 2015: return S_UserConnect;
        case 2034: return C_ReportUserLeaveState;
        case 2016: return S_NewRoomOwner;
        case 2017: return C_SendMessageInRoom;
        case 2018: return S_UserMessageInRoom;
        case 2019: return S_GameSyncOK;
        case 2200: return C_RoomSettingEnableSpeakInterrupt;
        case 2201: return S_RoomSettingEnableSpeakInterrupt;
        case 2202: return C_RoomSettingUserLevelLimit;
        case 2203: return S_RoomSettingUserLevelLimit;
        case 2204: return C_RoomSettingPWD;
        case 2205: return S_RoomSettingPWD;
        case 2206: return C_RoomSettingEnableSpectate;
        case 2207: return S_RoomSettingEnableSpectate;
        case 2208: return C_ReqChangeSeat;
        case 2209: return S_RespChangeSeat;
        case 2210: return S_UserChangeSeat;
        case 2021: return S_GameStart;
        case 2022: return S_GameResult;
        case 2023: return S_EnterStage;
        case 2076: return S_Timer;
        case 2025: return C_ChooseSeat;
        case 2026: return S_ChooseSeat;
        case 2027: return C_ConfirmUseAbility;
        case 2028: return S_TargetResult;
        case 2029: return S_RoleActionEnd;
        case 2030: return S_RoleUseAbility;
        case 2031: return S_Werewolves;
        case 2032: return S_WerewolvesActionResult;
        case 2033: return S_SeerActionResult;
        case 2077: return S_StartSpeakFrom;
        case 2036: return S_TurnSpeak;
        case 2037: return C_EndSpeak;
        case 2040: return S_EndSpeak;
        case 2078: return S_AllSpeakEnd;
        case 2038: return S_VoteResult;
        case 2039: return S_Death;
        case 2060: return S_SyncGameState;
        case 2061: return S_SyncSeerState;
        case 2062: return S_SyncWitchState;
        case 2063: return S_SyncDefenderState;
        case 2064: return S_SyncStage;
        case 2065: return S_SyncGameStageRecords;
        case 2068: return S_RunForSheriff;
        case 2069: return C_QuitSheriff;
        case 2070: return S_QuitSheriff;
        case 2071: return S_SheriffResult;
        case 2072: return S_SheriffActionResult;
        case 2073: return S_SheriffChooseSpeakFrom;
        case 2074: return C_WerewolfExpose;
        case 2075: return C_ConfirmResult;
        case 2079: return C_EnableCurSpeakInterrupt;
        case 2080: return S_EnableCurSpeakInterrupt;
        case 2081: return S_SelfRole;
        case 2082: return S_TargetRole;
        case 2083: return S_SyncONTroubleMakerState;
        case 2999: return ROUTER_GAME_END;
        case 3000: return ROUTER_KITSVR_BEGIN;
        case 3001: return C_ReqUserNetEaseToken;
        case 3002: return S_RespUserNetEaseToken;
        case 3003: return C_ReqRankData;
        case 3004: return S_RespRankData;
        case 3005: return C_ReqNewMail;
        case 3006: return S_RespNewMail;
        case 3007: return C_ReportGetNewMail;
        case 3008: return C_ReqFindUserByName;
        case 3009: return S_ResFindUserByName;
        case 3010: return C_ReqMatchRankData;
        case 3011: return S_RespMatchRankData;
        case 3012: return C_ReqGetAttachment;
        case 3013: return S_RespGetAttachment;
        case 3014: return C_ReqUserSnapshot;
        case 3015: return S_RespUserSnapshot;
        case 3016: return C_ReqBatchUserSnapshot;
        case 3017: return S_RespBatchUserSnapshot;
        case 3018: return C_ReqUserDetail;
        case 3019: return S_RespUserDetail;
        case 3020: return C_ReqMatchHonor;
        case 3021: return S_RespMatchHonor;
        case 3999: return ROUTER_KITSVR_END;
        case 4000: return ROUTER_CLUB_BEGIN;
        case 4001: return C_ReqMyClubs;
        case 4002: return S_RespMyClubs;
        case 4003: return C_ReqClubDetail;
        case 4004: return S_RespClubDetail;
        case 4005: return C_ReqClubMembers;
        case 4006: return S_RespClubMembers;
        case 4007: return C_ReqClubMembersOnlineStatus;
        case 4008: return S_RespClubMembersOnlineStatus;
        case 4009: return C_ReqTopClubs;
        case 4010: return S_RespTopClubs;
        case 4011: return C_ReqCreateClub;
        case 4012: return S_RespCreateClub;
        case 4013: return C_ReqApplyJoinClub;
        case 4014: return S_RespApplyJoinClub;
        case 4015: return C_ReqConfirmApplyJoinClub;
        case 4016: return S_RespConfirmApplyJoinClub;
        case 4017: return S_NoticeApplyJoinClubResult;
        case 4018: return C_ReqListApplyJoinClub;
        case 4019: return S_RespListApplyJoinClub;
        case 4020: return S_NoticeNewApplyJoinClub;
        case 4021: return C_ReqQuitClub;
        case 4022: return S_RespQuitClub;
        case 4023: return S_NoticeClubEvent;
        case 4024: return C_SendMessageInClub;
        case 4025: return S_NoticeClubUserMessage;
        case 4026: return C_ReqDisbandClub;
        case 4027: return S_RespDisbandClub;
        case 4028: return C_ReqChangeClubMemberJob;
        case 4029: return S_RespChangeClubMemberJob;
        case 4030: return C_ReqChangeClubAnnouncement;
        case 4031: return S_RespChangeClubAnnouncement;
        case 4032: return C_ReqClubMemberRooms;
        case 4033: return S_RespClubMemberRooms;
        case 4034: return C_ReqFindClubByName;
        case 4035: return S_RespFindClubByName;
        case 4036: return C_ReqKickClubMember;
        case 4037: return S_RespKickClubMember;
        case 4999: return ROUTER_CLUB_END;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Client>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Client> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Client>() {
            public Client findValueByNumber(int number) {
              return Client.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mapi.werewolf.opcode.ClientOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Client[] VALUES = values();

    public static Client valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Client(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mapi.werewolf.opcode.Client)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4sanguosha.com/werewolf/gameproto/opcod" +
      "e/client.proto\022\030com.mapi.werewolf.opcode" +
      "*\315*\n\006Client\022\027\n\023ClientInvaildOpCode\020\000\022\020\n\014" +
      "ReqHeartBeat\020\001\022\021\n\rRespHeartBeat\020\002\022\014\n\010Req" +
      "Login\020\003\022\r\n\tRespLogin\020\004\022\r\n\tReqLogout\020\005\022\020\n" +
      "\014NoticeLogout\020\006\022\026\n\022S_MessageInChannel\020\013\022" +
      "\027\n\022ROUTE_ENTITY_BEGIN\020\310\001\022\022\n\rC_ReqUserDat" +
      "a\020\311\001\022\023\n\016S_RespUserData\020\312\001\022\026\n\021C_ReqInitUs" +
      "erData\020\313\001\022\027\n\022S_RespInitUserData\020\314\001\022\026\n\021C_" +
      "ReqChangeAvatar\020\315\001\022\026\n\021S_ResChangeAvatar\020" +
      "\316\001\022\025\n\020C_ReqGameRecords\020\322\001\022\026\n\021S_RespGameR" +
      "ecords\020\323\001\022\031\n\024S_NoticeUserExpLevel\020\324\001\022\025\n\020" +
      "C_ReqBindAccount\020\325\001\022\026\n\021S_RespBindAccount" +
      "\020\326\001\022\027\n\022C_ReqUserMatchData\020\327\001\022\030\n\023S_RespUs" +
      "erMatchData\020\330\001\022\036\n\031C_ReqUserMatchGameReco" +
      "rds\020\331\001\022\037\n\032S_RespUserMatchGameRecords\020\332\001\022" +
      "\031\n\024C_ReqGoodsByCategory\020\333\001\022\032\n\025S_RespGood" +
      "sByCategory\020\334\001\022\022\n\rC_ReqAllGoods\020\335\001\022\023\n\016S_" +
      "RespAllGoods\020\336\001\022\022\n\rC_ReqAllTasks\020\337\001\022\023\n\016S" +
      "_RespAllTasks\020\340\001\022\023\n\016S_NtfTaskState\020\341\001\022\024\n" +
      "\017C_ReqChangeTask\020\342\001\022\025\n\020S_RespChangeTask\020" +
      "\343\001\022\024\n\017C_ReqMyActivity\020\344\001\022\025\n\020S_RespMyActi" +
      "vity\020\345\001\022\027\n\022C_ReqEditSignature\020\346\001\022\030\n\023S_Re" +
      "spEditSignature\020\347\001\022\026\n\021C_ReqUpLoadFigure\020" +
      "\350\001\022\027\n\022S_RespUpLoadFigure\020\351\001\022\025\n\020ROUTE_ENT" +
      "ITY_END\020\347\007\022\027\n\022ROUTER_LOBBY_BEGIN\020\350\007\022\027\n\022C" +
      "_ReqQuickJoinRoom\020\351\007\022\022\n\rC_ReqJoinRoom\020\203\010" +
      "\022\023\n\016S_RespJoinRoom\020\352\007\022\022\n\rC_ReqQuitRoom\020\353" +
      "\007\022\023\n\016S_RespQuitRoom\020\354\007\022\024\n\017C_ReqCreateRoo" +
      "m\020\204\010\022\025\n\020S_RespCreateRoom\020\205\010\022\030\n\023C_ReqAppl" +
      "yAddFriend\020\360\007\022\030\n\023S_ResApplyAddFriend\020\361\007\022" +
      "\032\n\025C_ReqConfirmAddFriend\020\362\007\022\032\n\025S_ResConf" +
      "irmAddFriend\020\363\007\022\023\n\016C_ReqDelFriend\020\364\007\022\023\n\016" +
      "S_ResDelFriend\020\365\007\022\024\n\017C_ReqFriendChat\020\366\007\022" +
      "\024\n\017S_ResFriendChat\020\367\007\022\026\n\021C_ReqFollowFrie" +
      "nd\020\370\007\022\026\n\021S_ResFollowFriend\020\371\007\022\024\n\017C_ReqFr" +
      "iendData\020\372\007\022\024\n\017S_ResFriendData\020\373\007\022\024\n\017C_R" +
      "eqFriendList\020\374\007\022\024\n\017S_ResFriendList\020\375\007\022\033\n" +
      "\026S_NoticeApplyAddFriend\020\376\007\022\035\n\030S_NoticeCo" +
      "nfirmAddFriend\020\377\007\022\026\n\021S_NoticeDelFriend\020\200" +
      "\010\022\026\n\021C_ReqFriendStatus\020\201\010\022\026\n\021S_ResFriend" +
      "Status\020\202\010\022\025\n\020C_InviteJoinRoom\020\206\010\022\033\n\026S_In" +
      "viteJoinRoomResult\020\207\010\022\035\n\030S_NoticeInviteT" +
      "oJoinRoom\020\210\010\022\027\n\022S_NoticeGameFreeze\020\211\010\022\023\n" +
      "\016C_ReqJoinMatch\020\213\010\022\024\n\017S_RespJoinMatch\020\214\010" +
      "\022\025\n\020C_ReqCancelMatch\020\215\010\022\026\n\021S_RespCancelM" +
      "atch\020\216\010\022\031\n\024C_ReqUserSignUpMatch\020\217\010\022\032\n\025S_" +
      "RespUserSignUpMatch\020\220\010\022\031\n\024C_ReqJoinChatC" +
      "hannel\020\221\010\022\032\n\025S_RespJoinChatChannel\020\222\010\022\031\n" +
      "\024C_ReqChatChannelList\020\223\010\022\032\n\025S_RespChatCh" +
      "annelList\020\224\010\022\033\n\026C_SendMessageInChannel\020\225" +
      "\010\022\031\n\024C_ReqQuitChatChannel\020\226\010\022\032\n\025S_RespQu" +
      "itChatChannel\020\227\010\022\031\n\024C_ReqCreateMatchRoom" +
      "\020\230\010\022\032\n\025S_RespCreateMatchRoom\020\231\010\022\027\n\022C_Req" +
      "JoinMatchRoom\020\232\010\022\030\n\023S_RespJoinMatchRoom\020" +
      "\233\010\022\025\n\020ROUTER_LOBBY_END\020\317\017\022\026\n\021ROUTER_GAME" +
      "_BEGIN\020\320\017\022\037\n\032C_ReportClientReadyForGame\020" +
      "\321\017\022\017\n\nC_ReqReady\020\322\017\022\020\n\013S_RespReady\020\323\017\022\025\n" +
      "\020C_ReqCancelReady\020\324\017\022\026\n\021S_RespCancelRead" +
      "y\020\325\017\022\027\n\022C_ReqRoomStartGame\020\326\017\022\030\n\023S_RespR" +
      "oomStartGame\020\327\017\022\032\n\025S_IsRoomAbleStartGame" +
      "\020\344\017\022\022\n\rC_ReqKickUser\020\330\017\022\023\n\016S_RespKickUse" +
      "r\020\331\017\022\025\n\020S_NoticeBeKicked\020\332\017\022\024\n\017S_SyncRoo" +
      "mState\020\333\017\022\017\n\nS_UserJoin\020\334\017\022\017\n\nS_UserQuit" +
      "\020\335\017\022\020\n\013S_UserReady\020\336\017\022\022\n\rS_UserConnect\020\337" +
      "\017\022\033\n\026C_ReportUserLeaveState\020\362\017\022\023\n\016S_NewR" +
      "oomOwner\020\340\017\022\030\n\023C_SendMessageInRoom\020\341\017\022\030\n" +
      "\023S_UserMessageInRoom\020\342\017\022\021\n\014S_GameSyncOK\020" +
      "\343\017\022&\n!C_RoomSettingEnableSpeakInterrupt\020" +
      "\230\021\022&\n!S_RoomSettingEnableSpeakInterrupt\020" +
      "\231\021\022 \n\033C_RoomSettingUserLevelLimit\020\232\021\022 \n\033" +
      "S_RoomSettingUserLevelLimit\020\233\021\022\025\n\020C_Room" +
      "SettingPWD\020\234\021\022\025\n\020S_RoomSettingPWD\020\235\021\022 \n\033" +
      "C_RoomSettingEnableSpectate\020\236\021\022 \n\033S_Room" +
      "SettingEnableSpectate\020\237\021\022\024\n\017C_ReqChangeS" +
      "eat\020\240\021\022\025\n\020S_RespChangeSeat\020\241\021\022\025\n\020S_UserC" +
      "hangeSeat\020\242\021\022\020\n\013S_GameStart\020\345\017\022\021\n\014S_Game" +
      "Result\020\346\017\022\021\n\014S_EnterStage\020\347\017\022\014\n\007S_Timer\020" +
      "\234\020\022\021\n\014C_ChooseSeat\020\351\017\022\021\n\014S_ChooseSeat\020\352\017" +
      "\022\030\n\023C_ConfirmUseAbility\020\353\017\022\023\n\016S_TargetRe" +
      "sult\020\354\017\022\024\n\017S_RoleActionEnd\020\355\017\022\025\n\020S_RoleU" +
      "seAbility\020\356\017\022\021\n\014S_Werewolves\020\357\017\022\035\n\030S_Wer" +
      "ewolvesActionResult\020\360\017\022\027\n\022S_SeerActionRe" +
      "sult\020\361\017\022\025\n\020S_StartSpeakFrom\020\235\020\022\020\n\013S_Turn" +
      "Speak\020\364\017\022\017\n\nC_EndSpeak\020\365\017\022\017\n\nS_EndSpeak\020" +
      "\370\017\022\022\n\rS_AllSpeakEnd\020\236\020\022\021\n\014S_VoteResult\020\366" +
      "\017\022\014\n\007S_Death\020\367\017\022\024\n\017S_SyncGameState\020\214\020\022\024\n" +
      "\017S_SyncSeerState\020\215\020\022\025\n\020S_SyncWitchState\020" +
      "\216\020\022\030\n\023S_SyncDefenderState\020\217\020\022\020\n\013S_SyncSt" +
      "age\020\220\020\022\033\n\026S_SyncGameStageRecords\020\221\020\022\024\n\017S" +
      "_RunForSheriff\020\224\020\022\022\n\rC_QuitSheriff\020\225\020\022\022\n" +
      "\rS_QuitSheriff\020\226\020\022\024\n\017S_SheriffResult\020\227\020\022" +
      "\032\n\025S_SheriffActionResult\020\230\020\022\035\n\030S_Sheriff" +
      "ChooseSpeakFrom\020\231\020\022\025\n\020C_WerewolfExpose\020\232" +
      "\020\022\024\n\017C_ConfirmResult\020\233\020\022\036\n\031C_EnableCurSp" +
      "eakInterrupt\020\237\020\022\036\n\031S_EnableCurSpeakInter" +
      "rupt\020\240\020\022\017\n\nS_SelfRole\020\241\020\022\021\n\014S_TargetRole" +
      "\020\242\020\022\036\n\031S_SyncONTroubleMakerState\020\243\020\022\024\n\017R" +
      "OUTER_GAME_END\020\267\027\022\030\n\023ROUTER_KITSVR_BEGIN" +
      "\020\270\027\022\032\n\025C_ReqUserNetEaseToken\020\271\027\022\033\n\026S_Res" +
      "pUserNetEaseToken\020\272\027\022\022\n\rC_ReqRankData\020\273\027" +
      "\022\023\n\016S_RespRankData\020\274\027\022\021\n\014C_ReqNewMail\020\275\027" +
      "\022\022\n\rS_RespNewMail\020\276\027\022\027\n\022C_ReportGetNewMa" +
      "il\020\277\027\022\030\n\023C_ReqFindUserByName\020\300\027\022\030\n\023S_Res" +
      "FindUserByName\020\301\027\022\027\n\022C_ReqMatchRankData\020" +
      "\302\027\022\030\n\023S_RespMatchRankData\020\303\027\022\027\n\022C_ReqGet" +
      "Attachment\020\304\027\022\030\n\023S_RespGetAttachment\020\305\027\022" +
      "\026\n\021C_ReqUserSnapshot\020\306\027\022\027\n\022S_RespUserSna" +
      "pshot\020\307\027\022\033\n\026C_ReqBatchUserSnapshot\020\310\027\022\034\n" +
      "\027S_RespBatchUserSnapshot\020\311\027\022\024\n\017C_ReqUser" +
      "Detail\020\312\027\022\025\n\020S_RespUserDetail\020\313\027\022\024\n\017C_Re" +
      "qMatchHonor\020\314\027\022\025\n\020S_RespMatchHonor\020\315\027\022\026\n" +
      "\021ROUTER_KITSVR_END\020\237\037\022\026\n\021ROUTER_CLUB_BEG" +
      "IN\020\240\037\022\021\n\014C_ReqMyClubs\020\241\037\022\022\n\rS_RespMyClub" +
      "s\020\242\037\022\024\n\017C_ReqClubDetail\020\243\037\022\025\n\020S_RespClub" +
      "Detail\020\244\037\022\025\n\020C_ReqClubMembers\020\245\037\022\026\n\021S_Re" +
      "spClubMembers\020\246\037\022!\n\034C_ReqClubMembersOnli" +
      "neStatus\020\247\037\022\"\n\035S_RespClubMembersOnlineSt" +
      "atus\020\250\037\022\022\n\rC_ReqTopClubs\020\251\037\022\023\n\016S_RespTop" +
      "Clubs\020\252\037\022\024\n\017C_ReqCreateClub\020\253\037\022\025\n\020S_Resp" +
      "CreateClub\020\254\037\022\027\n\022C_ReqApplyJoinClub\020\255\037\022\030" +
      "\n\023S_RespApplyJoinClub\020\256\037\022\036\n\031C_ReqConfirm" +
      "ApplyJoinClub\020\257\037\022\037\n\032S_RespConfirmApplyJo" +
      "inClub\020\260\037\022 \n\033S_NoticeApplyJoinClubResult" +
      "\020\261\037\022\033\n\026C_ReqListApplyJoinClub\020\262\037\022\034\n\027S_Re" +
      "spListApplyJoinClub\020\263\037\022\035\n\030S_NoticeNewApp" +
      "lyJoinClub\020\264\037\022\022\n\rC_ReqQuitClub\020\265\037\022\023\n\016S_R" +
      "espQuitClub\020\266\037\022\026\n\021S_NoticeClubEvent\020\267\037\022\030" +
      "\n\023C_SendMessageInClub\020\270\037\022\034\n\027S_NoticeClub" +
      "UserMessage\020\271\037\022\025\n\020C_ReqDisbandClub\020\272\037\022\026\n" +
      "\021S_RespDisbandClub\020\273\037\022\035\n\030C_ReqChangeClub" +
      "MemberJob\020\274\037\022\036\n\031S_RespChangeClubMemberJo" +
      "b\020\275\037\022 \n\033C_ReqChangeClubAnnouncement\020\276\037\022!" +
      "\n\034S_RespChangeClubAnnouncement\020\277\037\022\031\n\024C_R" +
      "eqClubMemberRooms\020\300\037\022\032\n\025S_RespClubMember" +
      "Rooms\020\301\037\022\030\n\023C_ReqFindClubByName\020\302\037\022\031\n\024S_" +
      "RespFindClubByName\020\303\037\022\030\n\023C_ReqKickClubMe" +
      "mber\020\304\037\022\031\n\024S_RespKickClubMember\020\305\037\022\024\n\017RO" +
      "UTER_CLUB_END\020\207\'b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
